### PR TITLE
Add extraEnv, extraVolumes, and extraVolumeMounts to prometheus-es-exporter

### PR DESCRIPTION
**Pull request by olegch**
Thank you for this package - comes very useful in our projects!

This pull request adds a few parameters to the package that are useful to specify the exporter parameters, certificates and credentials stored in secrets and config maps.

For example, if elastic password and certificates are stored in secrets, it becomes possible to configure the exporter as follows via values.yaml:

```
image:
  tag: '0.14.0'
container:
  extraArgs:
  - '--basic-user=es-user'
  - '--basic-password=$(ES_PASSWORD)'
  - '--ca-certs=/mnt/certs/cacerts'
  extraEnv:
  - name: ES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: es-credentials
        key: es-password
  extraVolumeMounts:
  - name: certs
    mountPath: /mnt/certs
pod:
  extraVolumes:
  - name: certs
    secret:
      secretName: es-credentials
```

I hope you will find it useful and merge.

I tried to follow the same conventions you established.
I also generated a new version of helm package tgz archive and regenerated `index.yaml`.

### CODE REVIEW

**Comment by spiegela** [comment]
@braedon I also need this fix to use an ES TLS cert. Was just about to fork to add it. Is there a blocker to merging?

**Comment by braedon** [comment]
Apologies, I missed this. I'll take a look tomorrow.

**Comment by spiegela** [comment]
Cool. Thanks. I'll also get another PR prepped for environment variable options so I can add basic auth support also.

**Comment by braedon** [comment]
Thanks for the PR @olegch, sorry it took me so long to get to it.

The additions look great. I'm going to merge into another branch so I can update the other chart as well, and update the minor version number. It should be in master in the next hour or so.

**Comment by braedon** [comment]
Version 0.2.0 should now be available in the helm repo with these changes.

**Comment by spiegela** [comment]
Perfect. Thanks!

**Pull request merged**
